= Лабораторная работа по Git
:source-highlighter: rouge
:rouge-style: github
:icons: font
:sectnums:

Данная лабораторная работа нацелена на получение праткических навыков работы с системой контроля версий Git.
В ней вам предстоит развернуть простую персональную страничку, используя сервис для хостинга статических страниц https://pages.github.com/[GitHub Pages].
Страницу будем верстать на языке https://daringfireball.net/projects/markdown/[Markdown],
из которого генератором статических сайтов https://jekyllrb.com/[jekyll]
(имеет https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll[встроенную поддержку в GitHub Pages])
будет создана веб-страница.

В процессе вы получите базовые навыки работы с Git и GitHub

* Задавать настройки Git
* Клонировать удалённый репозиторий себе на компьютер
* Создавать ветки и переключаться между ними
* Подготавливать изменения, которые должны войти в коммит
* Коммитить изменения в репозитории
* Просматривать историю изменений в репозитории
* Сливать изменения из разных веток и разрешать конфликты, возникающие при слиянии
* Изменять уже записанную историю
* Отправлять локальные изменения в удалённый репозиторий, и получать изменения из него
* Делать Pull Request'ы в GitHub

Также в конце вы найдёте список материалов для дальнейшего изучения Git и список использованных в лабораторной работе команд с их описанием

== Подготовка

[arabic]
. Зарегистрируйтесь на GitHub. Очень рекомендуем использовать "приличную почту", т.е что-то типа `имя.фамилия@gmail.com`, а не "`нагибатор228@gmail.com`"
. Установите себе на компьютер Git, задайте базовые настройки -- имя пользователя и email (они будут задавать автора коммитов)

[source, shell]
----
git config --global user.name '<Имя Фамилия>'
git config --global user.email '<Ваш email>'
----

== Создайте публичный репозиторий на GitHub
Задайте репозиторию имя, выберите лицензию, под которой исходный код в репозитории будет доступен,
напримеh _MIT License_

== Склонируйте созданный репозиторий на свой компьютер

[source, shell]
----
git clone <URL вашего репозитория>
----

== Создайте новую ветку `config` и переключитесь в неё

[source, shell]
----
git switch -c config
----

== Создайте файл `_config.yml` со следующим содержимым

[source, yaml]
----
title: <Тут напишите заголовок, например, "Имя Фамилия">
description: <Тут напишите какое-то описание>
----

== Добавьте сделанные изменения к будущему коммиту

[source, shell]
----
git add _config.yml
----

== Посмотрите изменения, которые войдут в коммит

[source, shell]
----
git diff --staged
----

Вы должны увидеть что-то подобное

[source, diff]
----
diff --git a/_config.yml b/_config.yml
new file mode 100644
index 0000000..fee889c
--- /dev/null
+++ b/_config.yml
@@ -0,0 +1,3 @@
+title: Vladimir Kutuev
+description: Personal page of Vladimir Kutuev hosted via GitHub Pages.
----

== Зафиксируйте изменения (коммит)

[source, shell]
----
git commit -m 'Add base jekyll configuration'
----

== Создайте новую ветку `config_theme` и переключитесь в неё

[source, shell]
----
git switch main
git switch -c config_theme
----

[NOTE]
====
Отметим, что некоторые шаги могут выглядеть довольно странно, однако они позволят создать конфликт,
что поможет научиться разрешать конфликты, а также помогут получить побольше опыта работы с ветками.
====

== Создайте файл `_config.yml` со следующим содержимым

[source, yaml]
----
theme: <Тема, например, jekyll-theme-hacker>
----

https://pages.github.com/themes/[Другие темы]

== Добавьте сделанные изменения к будущему коммиту

[source, shell]
----
git add _config.yml
----

== Зафиксируйте изменения

[source, shell]
----
git commit -m 'Add base jekyll configuration'
----

== Посмотрите, что история изменений нелинейна

[source, shell]
----
git log --graph --oneline --all
----

Вы должны увидеть что-то подобное

[source]
----
* 0bb0b9c (HEAD -> config_theme) Add jekyll theme
| * d8748cf (config) Add base jekyll configuration
|/
* 4a9ce37 (origin/main, origin/HEAD, main) Initial commit
----

== Выполните слияние ветки `config_theme` в ветку `config`

[source, shell]
----
git switch config
git merge config_theme
----

Вы должны увидеть что-то такое

[source]
----
Auto-merging _config.yml
CONFLICT (add/add): Merge conflict in _config.yml
Automatic merge failed; fix conflicts and then commit the result.
----

Это конфликт!

== Разрешите конфликт

Откройте файл `_config.yml`, он должен выглядеть как-то так

[source]
----
<<<<<<< HEAD
title: Vladimir Kutuev
description: Personal page of Vladimir Kutuev hosted via GitHub Pages.
=======
theme: jekyll-theme-hacker
>>>>>>> config_theme
----

Приведите файл в тот вид, который должен быть после слияния

[source, yaml]
----
title: Vladimir Kutuev
description: Personal page of Vladimir Kutuev hosted via GitHub Pages.
theme: jekyll-theme-hacker
----

Теперь продолжим слияние

[source, shell]
----
git add _config.yml
git merge --continue
----

Конфликт успешно разрешился, слияние выполнено

== Посмотрите историю _git_

[source, shell]
----
git log
----

Вы должны увидеть что-то такое

[source]
----
commit 26830abdcb9590325eafe8c0d83595649a78ceb8 (HEAD -> config)
Merge: d8748cf 0bb0b9c
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 08:43:57 2023 +0300

    Merge branch 'config_theme' into config

commit 0bb0b9cdd877038a75137d8d016c678b077a7e6f (config_theme)
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 08:29:03 2023 +0300

    Add jekyll theme

commit d8748cfb24e4c5150c875a4c826a29ea61bd8f81
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 08:00:40 2023 +0300

    Add base jekyll configuration

commit 4a9ce37aa4a3257450cdad68b2554f1f3b3a0abf (origin/main, origin/HEAD, main)
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Fri Aug 18 16:41:03 2023 +0300

    Initial commit
----

Также можно посмотреть на историю в виде дерева

[source, shell]
----
git log --graph --oneline --all
----

Вы должны увидеть что-то такое

[source]
----
*   26830ab (HEAD -> config) Merge branch 'config_theme' into config
|\
| * 0bb0b9c (config_theme) Add jekyll theme
* | d8748cf Add base jekyll configuration
|/
* 4a9ce37 (origin/main, origin/HEAD, main) Initial commit
----


== Создайте ветку `page`, которая растёт от ветки `main`

[source, shell]
----
git switch main
git switch -c page
----

== Создайте файл `index.md`, в котором напишите что-то о себе, например

[source, markdown]
----
# Образование
- Студент бакалавриата СПбГУ по направлению «Программная инженерия»

# Контакты
- email: <Ваш email>
----

Можете рассказать побольше о себе, о проектах, над которыми работали и т.д.

== Сделайте коммит

[source, shell]
----
git add index.md
git commit -m 'Add personal page'
----

== Добавьте что-то, что забыли, в `index.md`, например, ваш Telegram

[source, markdown]
----
# Образование
- Студент бакалавриата СПбГУ по направлению «Программная инженерия»

# Контакты
- email: <Ваш email>
- telegram: [<telegram-логин>](https://t.me/<telegram-login>)
----

== Отредактируйте предыдущий коммит, добавив в него новые изменениия

[source, shell]
----
git add index.md
git commit --amend
----

== Добавьте _layout_ в `index.md`

[source, markdown]
----
---
layout: default
---

# Образование
- Студент бакалавриата СПбГУ по направлению «Программная инженерия»

# Контакты
- email: <Ваш email>
- telegram: [<telegram-логин>](https://t.me/<telegram-login>)
----

== Сделайте коммит

Добавьте изменения в файле `index.md` к коммиту, посмотрев те изменения, которые добавляете

[source, shell]
----
git add -p index.md
----

Вы увидите что-то такое

[source, diff]
----
diff --git a/index.md b/index.md
index 6a5338f..fcf125e 100644
--- a/index.md
+++ b/index.md
@@ -1,3 +1,7 @@
+---
+layout: default
+---
+
 # Образование
 - Студент бакалавриата СПбГУ по направлению «Программная инженерия»

(1/1) Stage this hunk [y,n,q,a,d,e,?]?
----

Введите `y`

Сделайте коммит

[source, shell]
----
git commit -m 'Add layout to personal page'
----

== Посмотрите на дерево коммитов

[source, shell]
----
git log --graph --oneline --all
----

Вы увидите что-то такое

[source]
----
* 2f33fbd (HEAD -> page) Add layout to personal page
* 8b63734 Add personal page
| *   26830ab (config) Merge branch 'config_theme' into config
| |\
| | * 0bb0b9c (config_theme) Add jekyll theme
| |/
|/|
| * d8748cf Add base jekyll configuration
|/
* 4a9ce37 (origin/main, origin/HEAD, main) Initial commit
----

== Перебазируйте ветку `page` на ветку `config`, объединив коммиты ветки `page` в один

[source, shell]
----
git rebase -i config
----

Вы должны увидеть в редакторе что-то такое

[source]
----
pick 8b63734 Add personal page
pick 2f33fbd Add layout to personal page
----

А также инструкцию по тому, что можно сделать с коммитами

[source]
----
# Rebase e2ac1d1..f9bb225 onto e2ac1d1 (1 command)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
#                    commit's log message, unless -C is used, in which case
#                    keep only this commit's message; -c is same as -C but
#                    opens the editor
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
#         create a merge commit using the original merge commit's
#         message (or the oneline, if no original merge commit was
#         specified); use -c <commit> to reword the commit message
# u, update-ref <ref> = track a placeholder for the <ref> to be updated
#                       to this position in the new commits. The <ref> is
#                       updated at the end of the rebase
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
----

Отредактируйте так, чтобы объединить коммиты

[source]
----
pick 8b63734 Add personal page
s 2f33fbd Add layout to personal page
----

Затем надо будет отредактировать сообщение к объединённому коммиту, оставьте

[source]
----
Add personal page
----

== Посмотрите на дерево коммитов

[source, shell]
----
git log --graph --oneline --all
----

Вы должны увидеть, что ветка `page` теперь "растёт" не из `main`, а из `config`

[source]
----
* 3b9b1d4 (HEAD -> page) Add personal page
*   26830ab (config) Merge branch 'config_theme' into config
|\
| * 0bb0b9c (config_theme) Add jekyll theme
* | d8748cf Add base jekyll configuration
|/
* 4a9ce37 (origin/main, origin/HEAD, main) Initial commit
----

== Посмотрите, что объединённый коммит содержит изменения 2х коммитов, которые делали выше

[source, shell]
----
git show
----

Вы должны увидеть что-то такое

[source, diff]
----
commit 3b9b1d4b57843a6d489aba9a0d0911e71c24aa9e (HEAD -> page)
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 09:30:43 2023 +0300

    Add personal page

diff --git a/index.md b/index.md
new file mode 100644
index 0000000..fcf125e
--- /dev/null
+++ b/index.md
@@ -0,0 +1,10 @@
+---
+layout: default
+---
+
+# Образование
+- Студент бакалавриата СПбГУ по направлению «Программная инженерия»
+
+# Контакты
+- email: <Ваш email>
+- telegram: [<telegram-логин>](https://t.me/<telegram-login>)
----

== Отправьте изменения ветки `page` в удалённый репозиторий

[source, shell]
----
git push
----

Однако _git_ этого не сделает и напишет

[source]
----
fatal: The current branch config has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin page

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
----

Это происходит из-за того, что в удалённом репозитории нет соответствующей ветки.
Выполните

[source, shell]
----
git push --set-upstream origin page
----

Теперь в выводе `git log` видим, что есть удалённая ветка `origin/page`, которая содержит то же, что и ветка `page`

[source]
----
commit 3b9b1d4b57843a6d489aba9a0d0911e71c24aa9e (HEAD -> page, origin/page)
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 09:30:43 2023 +0300

    Add personal page
----

== Сделайте Pull Request ветки `page` в ветку `main` на GitHub

Укажите заколовок Pull Reques'а, например, `Add personal page`

Напишите описание Pull Request'a, например

[source, markdown]
----
Add
- Simple personal page
- `jekyll` config
----

== Влейте Pull Request

Рядом с кнопкой `Merge pull request` есть треугольник для выбора способа добавления изменений

Выберите `Squash and merge` и выполните слияние

== В локальном репозитории подтяните изменения из удалённого репозитория

[source]
----
git switch main
git pull
----

В выводе `git log` Вы увидите, что добавился коммит, созданный в результате Pull Request'а

[source]
----
commit ee2783f6b1b6720ad694233fd438022e29c0dc90 (HEAD -> main, origin/main, origin/HEAD)
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Sat Aug 19 10:13:24 2023 +0300

    Add personal page (#1)

    * Add base jekyll configuration

    * Add jekyll theme

    * Add personal page

commit 4a9ce37aa4a3257450cdad68b2554f1f3b3a0abf
Author: Vladimir Kutuev <vladimir.kutuev@gmail.com>
Date:   Fri Aug 18 16:41:03 2023 +0300

    Initial commit
----

== Разверните страничку

В настройках репозитория на GitHub во вкладке `Pages` выберите ветку,
из которой будет производиться развёртывание, указав `main`

Теперь по ссылке `+https://<Ваш GitHub-login>.github.io/<Имя репозитория>/+`
доступна ваша персональная страничка

== Продолжайте изучать Git :)

[glossary]
== Использованные команды

`git config --global <имя опции> <значение>`:: Установить глобальные опции; опции `user.name` и `user.email` определяют, что в коммитае будет указано про автора
`git clone <URL репозитория>`:: Склонировать удалённый репозиторий на компьютер
`git switch <имя ветки>`:: Переключиться на ветку с указанным именем
`git switch -c <имя ветки>` или `git switch --create <имя ветки>`:: Создать ветку с указанным именем и переключиться на неё
`git add <пути до файлов>`:: Добавить изменения в файле в "индекс" -- снимок рабочего дерева, содержимое которого войдёт в следующий коммит
`git add -p <пути до файлов>` или `git add --patch <пути до файлов>`:: В интерактивном режиме выбрать фрагменты изменений, которые нужно добавить в индекс (позволяет посмотреть изменения перед добавлением в индекс)
`git diff --staged`:: Посмотреть изменения, которые находятся в индексе (разница между индексом и последним коммитом)
`git commit -m <сообщение к коммиту>` или `git commit --message=<сообщение к комиту>`:: Создать новый коммит, содержащий текущее содержимое индекса и данное сообщение, описывающее изменения. Если не передан флаг `-m|--message`, откроется редактор, в котором необходимо указать сообщение.
`git commit --amend`:: Изменить последний коммит, добавив к нему изменения из индекса; также позволяет изменить сообщение к коммиту
`git log`:: Показать журнал коммитов.
`git log --graph --oneline --all`:: Показать журнал коммитов для всех веток и тегов и удалённых репозиториев в виде дерева с кратким описанием коммитов (`<хеш> <сообщение>`)
`git show`:: Показать содержимое последнего коммита
`git merge <имя ветки>`:: Влить изменения из указанной ветки в текущую
`git merge --continue`:: В случае возникновения конфликта при `git merge <имя ветки>` после его разрешения продолжить слияние (также можно использовать `git commit`); если при возникновении конфликта хочется отменить слияние, используйте `git merge --abort`
`git rebase -i <имя ветки>` или `git rebase --interactive <имя ветки>`:: Интерактивно перебазировать текущую ветку на указанную. Запускает редактор для ввода команд того, как каждый коммит будет перенесен
`git push`:: Отправить изменения текущей ветки в соответствующую (отслеживаемую) ветку удалённого репозитория
`git push -u origin` или `git push --set-upstream origin <имя ветки>`:: Отправить изменения указанной ветки в удалённый репозиторий, указав, что необходимо отслеживать указанную ветку
`git pull`:: Получить изменения соответствующей (текущей ветке) ветки из удалённого репозитория и сразу влить их в текущую ветку
